package telas.ControleCheque;


import Controller.ClienteController;
import Controller.ControleChequeController;
import Controller.MunicipiosController;
import Regras.Formatacao;
import com.toedter.calendar.JTextFieldDateEditor;
import facade.ClienteFacade;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.smartcardio.Card;
import javax.swing.JOptionPane;
import model.Chequefechacaixa;
import model.Cliente;
import model.Clienteendereco;
import model.Clientefechamento;
import model.Controlecheques;
import model.Fechacaixa;
import model.Municipios;
import telas.Municipios.FrmConsultaMunicipios;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmCadastrarCheques.java
 *
 * Created on 08/11/2011, 09:10:58

package Interface;

import model.Cliente;
import model.Controlecheques;

/**
 *
 * @author Wolverine
 */
public class FrmCadastrarCheques extends javax.swing.JFrame implements IControleCheques{
    
    private String datePattern;
    private String maskPattern;
    private char placeHolder;
    
    private Controlecheques cheque;
    private Cliente cliente;
    private Clienteendereco clienteEndereco;
    private String cpf ="";
    private Clientefechamento clientefechamento;
    private Fechacaixa fechaCaixa;
    private IControleCheques telaCheque;
    private Municipios municipios;

    /** Creates new form FrmCadastrarCheques */
    public FrmCadastrarCheques(Fechacaixa fechaCaixa, IControleCheques telaCheque) {
        datePattern = "dd/MM/yyyy";
        maskPattern = "##/##/##";
        placeHolder = '_';
        this.telaCheque = telaCheque;
        this.fechaCaixa = fechaCaixa;
        cliente = new Cliente();
        clienteEndereco = new Clienteendereco();
        cheque = new Controlecheques();
        initComponents();
        dataCompensacaojDateChooser.setDate(new Date());
        dataEmissaojDateChooser.setDate(new Date());
        URL url = this.getClass().getResource("/imagens/logo_mini.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tipoClientejComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cpfjFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        nomejTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tipoLogradourojTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        logradourojTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        numerojTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        complementojTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cepjFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        cidadejTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        foneResidencialjFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        emailjTextField = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        bairrojTextField = new javax.swing.JTextField();
        foneCelularjFormattedTextField = new javax.swing.JFormattedTextField();
        jButton4 = new javax.swing.JButton();
        estadojTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        numeroBancojTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        agenciajTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        contaCorrentejTextField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        numeroChequejTextField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        dataEmissaojDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
            maskPattern, placeHolder));
    jLabel19 = new javax.swing.JLabel();
    valorChequejTextField = new javax.swing.JTextField();
    jLabel20 = new javax.swing.JLabel();
    dataCompensacaojDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
        maskPattern, placeHolder));
jLabel21 = new javax.swing.JLabel();
situacaojTextField = new javax.swing.JTextField();
preDatadojComboBox = new javax.swing.JComboBox();
jLabel22 = new javax.swing.JLabel();
jLabel23 = new javax.swing.JLabel();
trocajComboBox = new javax.swing.JComboBox();
jLabel24 = new javax.swing.JLabel();
observacoesjTextField = new javax.swing.JTextField();
jPanel15 = new javax.swing.JPanel();
jButton10 = new javax.swing.JButton();
jButton11 = new javax.swing.JButton();

setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
setTitle("Controle de Cheques ");

jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

tipoClientejComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PF", "PJ" }));
tipoClientejComboBox.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        tipoClientejComboBoxActionPerformed(evt);
    }
    });

    jLabel1.setText("Tipo Cliente");

    jLabel2.setText("CPF / CNPJ");

    cpfjFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cpfjFormattedTextFieldActionPerformed(evt);
        }
    });
    cpfjFormattedTextField.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            cpfjFormattedTextFieldFocusGained(evt);
        }
    });
    cpfjFormattedTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            cpfjFormattedTextFieldKeyPressed(evt);
        }
    });

    jLabel3.setText("Nome do Cliente");

    nomejTextField.setEditable(false);

    jLabel4.setText("Tipo Logradouro");

    tipoLogradourojTextField.setEditable(false);

    jLabel5.setText("Logradouro");

    logradourojTextField.setEditable(false);

    jLabel6.setText("Número");

    numerojTextField.setEditable(false);

    jLabel7.setText("Complemento");

    complementojTextField.setEditable(false);

    jLabel8.setText("Cep");

    cepjFormattedTextField.setEditable(false);

    jLabel9.setText("Cidade");

    cidadejTextField.setEditable(false);

    jLabel10.setText("Estado");

    jLabel11.setText("Telefone Rsidencial");

    foneResidencialjFormattedTextField.setEditable(false);

    jLabel12.setText("Fone Celular");

    jLabel13.setText("E-mail");

    emailjTextField.setEditable(false);

    jLabel25.setText("Bairro");

    bairrojTextField.setEditable(false);

    foneCelularjFormattedTextField.setEditable(false);

    jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/magnifier.png"))); // NOI18N
    jButton4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton4ActionPerformed(evt);
        }
    });

    estadojTextField.setEditable(false);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tipoClientejComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(31, 31, 31)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cpfjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(nomejTextField)))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(foneResidencialjFormattedTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(foneCelularjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel13)
                        .addComponent(emailjTextField)))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(complementojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cepjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel25)
                        .addComponent(bairrojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cidadejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(estadojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jButton4))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tipoLogradourojTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(logradourojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(numerojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(jLabel2)
                .addComponent(jLabel3))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tipoClientejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cpfjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(nomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4)
                .addComponent(jLabel5)
                .addComponent(jLabel6))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tipoLogradourojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(logradourojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(numerojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel7)
                .addComponent(jLabel10)
                .addComponent(jLabel9)
                .addComponent(jLabel8)
                .addComponent(jLabel25))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(complementojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cidadejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cepjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bairrojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estadojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jButton4))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel11)
                .addComponent(jLabel12)
                .addComponent(jLabel13))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(foneResidencialjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(emailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(foneCelularjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(21, Short.MAX_VALUE))
    );

    jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jLabel14.setText("Nº do Banco");

    jLabel15.setText("Agencia");

    jLabel16.setText("Conta Corrente");

    jLabel17.setText("Nº Cheque");

    jLabel18.setText("Data Emissão");

    dataEmissaojDateChooser.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            dataEmissaojDateChooserFocusGained(evt);
        }
    });

    jLabel19.setText("Valor do Cheque R$");

    valorChequejTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    valorChequejTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            valorChequejTextFieldKeyReleased(evt);
        }
    });

    jLabel20.setText("Data Compensação");

    dataCompensacaojDateChooser.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            dataCompensacaojDateChooserFocusGained(evt);
        }
    });

    jLabel21.setText("Situação");

    situacaojTextField.setEditable(false);
    situacaojTextField.setText("Caixa");

    preDatadojComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NAO", "SIM" }));

    jLabel22.setText("Pré Datado");

    jLabel23.setText("Troca");

    trocajComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NAO", "SIM" }));

    jLabel24.setText("Observações");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(observacoesjTextField)
                .addComponent(jLabel24)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(numeroBancojTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel15)
                        .addComponent(agenciajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel17))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(contaCorrentejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(numeroChequejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(19, 19, 19)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel18)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(dataEmissaojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(valorChequejTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(26, 26, 26)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(dataCompensacaojDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(situacaojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel21)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel22)
                        .addComponent(preDatadojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(trocajComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel23)
                            .addGap(0, 0, Short.MAX_VALUE)))))
            .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel14)
                .addComponent(jLabel15)
                .addComponent(jLabel16)
                .addComponent(jLabel17)
                .addComponent(jLabel18))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroBancojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agenciajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contaCorrentejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroChequejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(dataEmissaojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(valorChequejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(dataCompensacaojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(situacaojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(preDatadojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trocajComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel24)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(observacoesjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel15.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tick.png"))); // NOI18N
    jButton10.setText("Confirmar");
    jButton10.setToolTipText("Confirmar Inclusão de Cheque");
    jButton10.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton10ActionPerformed(evt);
        }
    });

    jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cross.png"))); // NOI18N
    jButton11.setText("Cancelar");
    jButton11.setToolTipText("Cancelar Inclusão de Cheque");
    jButton11.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton11ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
    jPanel15.setLayout(jPanel15Layout);
    jPanel15Layout.setHorizontalGroup(
        jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
            .addContainerGap(114, Short.MAX_VALUE)
            .addComponent(jButton10)
            .addGap(101, 101, 101)
            .addComponent(jButton11)
            .addGap(132, 132, 132))
    );
    jPanel15Layout.setVerticalGroup(
        jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel15Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton10)
                .addComponent(jButton11))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap(33, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipoClientejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoClientejComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoClientejComboBoxActionPerformed

    private void dataEmissaojDateChooserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataEmissaojDateChooserFocusGained

    }//GEN-LAST:event_dataEmissaojDateChooserFocusGained

    private void dataCompensacaojDateChooserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataCompensacaojDateChooserFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dataCompensacaojDateChooserFocusGained

    private void cpfjFormattedTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpfjFormattedTextFieldKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            cpf = cpfjFormattedTextField.getText();
            ClienteFacade clienteFacade = new ClienteFacade();
            try {
                cliente = clienteFacade.consultarDocFederal(cpfjFormattedTextField.getText());
                if (cliente==null){
                    JOptionPane.showMessageDialog(rootPane, "Cliente não Localizado");
                    preecherClienteNovo();
                    
                }else {
                    preecherCliente();
                    numeroBancojTextField.requestFocus();
                }
            } catch (SQLException ex) {
                Logger.getLogger(FrmCadastrarCheques.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane, "Erro Consultar Cliente " + ex);
            }
        }
    }//GEN-LAST:event_cpfjFormattedTextFieldKeyPressed

    private void cpfjFormattedTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpfjFormattedTextFieldFocusGained
        String tipo = (String) tipoClientejComboBox.getSelectedItem();
            if (tipo.equalsIgnoreCase("PF")){
            try {
                cpfjFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
                cpfjFormattedTextField.setText(cpf);
            } catch (ParseException ex) {
                Logger.getLogger(FrmCadastrarCheques.class.getName()).log(Level.SEVERE, null, ex);
            }
            }else {
            try {
                cpfjFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
                cpfjFormattedTextField.setText(cpf);
            } catch (ParseException ex) {
                Logger.getLogger(FrmCadastrarCheques.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
    }//GEN-LAST:event_cpfjFormattedTextFieldFocusGained

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if (validarCampos()){
            salvarDados();
            this.telaCheque.setModelCehques();
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void cpfjFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfjFormattedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfjFormattedTextFieldActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void valorChequejTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorChequejTextFieldKeyReleased
        valorChequejTextField.setText(Formatacao.decinalValorMonetario(valorChequejTextField.getText()));
    }//GEN-LAST:event_valorChequejTextFieldKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new FrmConsultaMunicipios(this);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField agenciajTextField;
    private javax.swing.JTextField bairrojTextField;
    private javax.swing.JFormattedTextField cepjFormattedTextField;
    private javax.swing.JTextField cidadejTextField;
    private javax.swing.JTextField complementojTextField;
    private javax.swing.JTextField contaCorrentejTextField;
    private javax.swing.JFormattedTextField cpfjFormattedTextField;
    private com.toedter.calendar.JDateChooser dataCompensacaojDateChooser;
    private com.toedter.calendar.JDateChooser dataEmissaojDateChooser;
    private javax.swing.JTextField emailjTextField;
    private javax.swing.JTextField estadojTextField;
    private javax.swing.JFormattedTextField foneCelularjFormattedTextField;
    private javax.swing.JFormattedTextField foneResidencialjFormattedTextField;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField logradourojTextField;
    private javax.swing.JTextField nomejTextField;
    private javax.swing.JTextField numeroBancojTextField;
    private javax.swing.JTextField numeroChequejTextField;
    private javax.swing.JTextField numerojTextField;
    private javax.swing.JTextField observacoesjTextField;
    private javax.swing.JComboBox preDatadojComboBox;
    private javax.swing.JTextField situacaojTextField;
    private javax.swing.JComboBox tipoClientejComboBox;
    private javax.swing.JTextField tipoLogradourojTextField;
    private javax.swing.JComboBox trocajComboBox;
    private javax.swing.JTextField valorChequejTextField;
    // End of variables declaration//GEN-END:variables

    private void preecherCliente(){
        ClienteFacade clienteFacade = new ClienteFacade();
        //Dados do Cliente
        nomejTextField.setText(cliente.getNome());
        nomejTextField.setEditable(false);
        try {
            //dados do endereco
            
            clienteEndereco = clienteFacade.consultarClienteEndereco(cliente.getIdcliente());
            if (clienteEndereco==null){
                JOptionPane.showMessageDialog(rootPane, "Enderço do Cliente não Localizado");
            }else {
                tipoLogradourojTextField.setText(clienteEndereco.getTipoLogradouro());
                tipoLogradourojTextField.setEditable(false);
                logradourojTextField.setText(clienteEndereco.getLogradouro());
                logradourojTextField.setEditable(false);
                numerojTextField.setText(clienteEndereco.getNumero());
                numerojTextField.setEditable(false);
                complementojTextField.setText(clienteEndereco.getComplemento());
                complementojTextField.setEditable(false);
                bairrojTextField.setText(clienteEndereco.getBairro());
                bairrojTextField.setEditable(false);
                cepjFormattedTextField.setText(clienteEndereco.getCep());
                cepjFormattedTextField.setEditable(false);
                cidadejTextField.setEditable(false);
                emailjTextField.setText(cliente.getEmail());
                emailjTextField.setEditable(false);
                foneCelularjFormattedTextField.setText(cliente.getFoneCelular());
                foneCelularjFormattedTextField.setEditable(false);
                foneResidencialjFormattedTextField.setText(cliente.getFoneFixo());
                foneResidencialjFormattedTextField.setEditable(false);
                if (clienteEndereco.getMunicipios()==0){
                    resetMunicipio();
                }else {
                    MunicipiosController municipiosController = new MunicipiosController();
                    municipios = municipiosController.getMunicipio(clienteEndereco.getMunicipios());
                    estadojTextField.setText(municipios.getEstado());
                    cidadejTextField.setText(clienteEndereco.getCidade());
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmCadastrarCheques.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "Erro Consultar endereco Cliente " + ex);
        }
    }
    
     private void preecherClienteNovo(){
         cliente = new Cliente();
         setMascaras();
        nomejTextField.setEditable(true);
        tipoLogradourojTextField.setEditable(true);
        logradourojTextField.setEditable(true);
        numerojTextField.setEditable(true);
        complementojTextField.setEditable(true);
        bairrojTextField.setEditable(true);
        cepjFormattedTextField.setEditable(true);
        foneCelularjFormattedTextField.setEditable(true);
        foneResidencialjFormattedTextField.setEditable(true);
        emailjTextField.setEditable(true);
        nomejTextField.requestFocus();
    }
    
    public final void  setMascaras(){
        try {
            foneCelularjFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
            foneResidencialjFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
            cepjFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (ParseException ex) {
            Logger.getLogger(FrmCadastrarCheques.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private boolean validarCampos(){
        cliente.setDocFederal(cpfjFormattedTextField.getText());
        if (cliente.getDocFederal().equalsIgnoreCase(null)){
            JOptionPane.showMessageDialog(rootPane, "Erro Cliente não Localizado");
            return false;
        }
        if (numeroBancojTextField.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Numero do Banco não preechido");
            return false;
        }
        if (agenciajTextField.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Agencia não preenchida");
            return false;
        }
        if (contaCorrentejTextField.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Conta Corrente não preenchida");
            return false;
        }
        if (numeroChequejTextField.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Nunero do Cheque não preenchido");
            return false;
        }
        if (valorChequejTextField.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Valor do Cheque não preenchido");
            return false;
        }
        if (dataEmissaojDateChooser.getDate()==null){
            JOptionPane.showMessageDialog(rootPane, "Data Emissão inválida");
            return false;
        }
        if (dataCompensacaojDateChooser.getDate()==null){
            JOptionPane.showMessageDialog(rootPane, "Data de Compensação inválida");
            return false;
        }
        if (this.municipios==null){
            JOptionPane.showMessageDialog(rootPane, "Municipio não consultado");
            return  false;
        }
        return true;
    }
    
    private void salvarDados(){
        ClienteController clienteController = new ClienteController();
        if (cliente.getIdcliente()==null){
            cliente.setDocFederal(cpfjFormattedTextField.getText());
            cliente.setTipo(tipoClientejComboBox.getSelectedItem().toString());
            cliente.setNome(nomejTextField.getText());
            cliente.setSituacao("ATIVO");
            cliente.setDataCadastro(new Date());
            cliente.setEmail(emailjTextField.getText());
            cliente.setFoneCelular(foneCelularjFormattedTextField.getText());
            cliente.setFoneFixo(foneResidencialjFormattedTextField.getText());
            cliente.setOperacao(2);
            cliente = clienteController.salvarCliente(cliente);
            clientefechamento = new Clientefechamento();
            clientefechamento.setClienteIdcliente(cliente.getIdcliente());
            clientefechamento.setDiaPagamento(1);
            clientefechamento.setFormaPagamento("Cheque");
            clientefechamento.setLimiteCredito(0.0);
            clientefechamento.setNotaFiscal("NAO");
            clientefechamento.setTipoFechamento("Diario");
            clienteController.salvarFechamento(clientefechamento);
        }
        if (clienteEndereco.getIdclienteEndereco()==null){
            clienteEndereco.setTipoLogradouro(tipoLogradourojTextField.getText());
            clienteEndereco.setLogradouro(logradourojTextField.getText());
            clienteEndereco.setNumero(numerojTextField.getText());
            clienteEndereco.setComplemento(complementojTextField.getText());
            clienteEndereco.setBairro(bairrojTextField.getText());
            clienteEndereco.setCep(cepjFormattedTextField.getText());
            if (this.municipios!=null){
                clienteEndereco.setCidade(municipios.getNomeMunicipio());
                clienteEndereco.setEstado(municipios.getEstado());
                clienteEndereco.setMunicipios(municipios.getIdmunicipios());
            }
            clienteEndereco.setClienteIdcliente(cliente.getIdcliente());
            clienteController.salvarEndereco(clienteEndereco);
            
        }
        ControleChequeController controleChequeController = new ControleChequeController();
        cheque.setAgencia(agenciajTextField.getText());
        cheque.setBanco(numeroBancojTextField.getText());
        cheque.setChequeTroca(trocajComboBox.getSelectedItem().toString());
        cheque.setCliente(cliente.getIdcliente());
        cheque.setContaCorrente(contaCorrentejTextField.getText());
        cheque.setDataCompensacao(dataCompensacaojDateChooser.getDate());
        cheque.setDataEmissao(dataEmissaojDateChooser.getDate());
        cheque.setNumeroCheque(numeroChequejTextField.getText());
        cheque.setPreDatado(preDatadojComboBox.getSelectedItem().toString());
        cheque.setSituacao(situacaojTextField.getText());
        cheque.setValorCheque(Formatacao.ConvercaoMonetariaDouble(valorChequejTextField.getText()));
        cheque.setEmpresa(this.fechaCaixa.getEmpresa());
        cheque = controleChequeController.salvarCehque(cheque);
        salvarChequefechacaixa();
        this.dispose();
    }
    
    public void salvarChequefechacaixa(){
        ControleChequeController controleChequeController = new ControleChequeController();
        Chequefechacaixa chequefechacaixa = new Chequefechacaixa();
        chequefechacaixa.setControlecheques(cheque.getIdControleCheques());
        chequefechacaixa.setFechacaixa(this.fechaCaixa.getIdfechaCaixa());
        controleChequeController.salvarCehqueFechaCaixa(chequefechacaixa);
    }

    public void setModelCehques() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void setMunicipios(Municipios municipios) {
      if (municipios!=null){
            this.municipios = municipios;
            cidadejTextField.setText(this.municipios.getNomeMunicipio());
            estadojTextField.setText(this.municipios.getEstado());
        }
    }

    public void resetMunicipio() {
        this.municipios=null;
        cidadejTextField.setText("");
        estadojTextField.setText("");
    }
}
