/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.formaRecebimento;

import Controller.BandeiraCartaoController;
import Controller.FormaPagamentoController;
import Interface.FormaPagamentoTableModel;
import Regras.Formatacao;
import controler.ItelaVenda;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import model.Bandeirascartao;
import model.Formapagamento;

/**
 *
 * @author wolverine
 */
public class FrmRecebimentoCartao extends javax.swing.JFrame {
    
    private List<Bandeirascartao> listaBandeira;
    private List<Formapagamento> listaFormaPagamentoCartao;
    private DefaultListModel itensBandeira;
    private DefaultListModel itensFormas;
    private ItelaVenda telaVenda;
    private FormaPagamentoTableModel modelForma;
    private List<Formapagamento> formaRecebidas;
    private double valorPagar;
    
    

    /**
     * Creates new form FrmRecebimentoCartao
     */
    public FrmRecebimentoCartao(ItelaVenda telaVenda, String valor) {
        this.telaVenda = telaVenda;
        initComponents();
        URL url = this.getClass().getResource("/imagens/logo_mini.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        this.setLocationRelativeTo(null);
        gerarListaBandeirasCartao();
        gerarModelFormaPagamento();
        valorjTextField.setText(valor);
        this.valorPagar = Formatacao.ConvercaoMonetariaDouble(valor);
        bandeirajTextField.requestFocus();
        numeroParcelasjTextField.setText("01");
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bandeirajTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        bandeirajList = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        formaPagamentojList = new javax.swing.JList();
        numeroParcelasjTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        valorjTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        formaPagamentojTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        formaPagamentojTable = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Forma de Pagamento Cartão");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bandeirajTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bandeirajTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        bandeirajTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bandeirajTextFieldKeyPressed(evt);
            }
        });

        bandeirajList.setBackground(new java.awt.Color(255, 0, 0));
        bandeirajList.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jScrollPane2.setViewportView(bandeirajList);

        formaPagamentojList.setBackground(new java.awt.Color(0, 102, 0));
        formaPagamentojList.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        formaPagamentojList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(formaPagamentojList);

        numeroParcelasjTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        numeroParcelasjTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        numeroParcelasjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                numeroParcelasjTextFieldKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Bandeira (Maquina)");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("No. Parcelas");

        valorjTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        valorjTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        valorjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                valorjTextFieldKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Valor R$");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Código Forma");

        formaPagamentojTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        formaPagamentojTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        formaPagamentojTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formaPagamentojTextFieldKeyPressed(evt);
            }
        });

        formaPagamentojTable.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        formaPagamentojTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(formaPagamentojTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bandeirajTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                            .addComponent(numeroParcelasjTextField)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(formaPagamentojTextField)
                            .addComponent(jLabel3)
                            .addComponent(valorjTextField))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bandeirajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numeroParcelasjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formaPagamentojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        jMenuItem1.setText("Confirmar Cartão");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem2.setText("Cancelar Cartão");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bandeirajTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bandeirajTextFieldKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            int idBandeira = Integer.parseInt(bandeirajTextField.getText());
            boolean verifica = false;
            for (int i=0;i<listaBandeira.size();i++){
                if (listaBandeira.get(i).getIdbandeirasCartao()==idBandeira){
                    bandeirajList.setSelectedIndex(i);
                    verifica = true;
                }
            }
            if (verifica){
                gerarListaFormasPagamento(idBandeira);
                numeroParcelasjTextField.requestFocus();
                numeroParcelasjTextField.selectAll();
            }else {
                JOptionPane.showMessageDialog(rootPane, "Bandeira não encontrada");
            }
        }
    }//GEN-LAST:event_bandeirajTextFieldKeyPressed

    private void numeroParcelasjTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroParcelasjTextFieldKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            formaPagamentojTextField.requestFocus();
            formaPagamentojTextField.selectAll();
        }
    }//GEN-LAST:event_numeroParcelasjTextFieldKeyPressed

    private void formaPagamentojTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formaPagamentojTextFieldKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            int idforma = Integer.parseInt(formaPagamentojTextField.getText());
            boolean verifica = false;
            for (int i=0;i<listaFormaPagamentoCartao.size();i++){
                if (listaFormaPagamentoCartao.get(i).getIdformaPagamento()==idforma){
                    formaPagamentojList.setSelectedIndex(i);
                    verifica = true;
                }
            }
            if (verifica){
                valorjTextField.requestFocus();
                valorjTextField.selectAll();
            }else {
                JOptionPane.showMessageDialog(rootPane, "Cartão não encontrada");
            }
        }
    }//GEN-LAST:event_formaPagamentojTextFieldKeyPressed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       for(int i=0; i<formaRecebidas.size();i++){
            formaRecebidas.get(i).setValor(0.0f);
            salvarFormaPagamento(formaRecebidas.get(i));
        }
       this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void valorjTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorjTextFieldKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            Formapagamento fp = new Formapagamento();
            fp = (Formapagamento) formaPagamentojList.getSelectedValue();
            fp.setValor(Formatacao.ConvercaoMonetariaFloat(valorjTextField.getText()));
            fp.setNumeroParcelas(Integer.parseInt(numeroParcelasjTextField.getText()));
            salvarFormaPagamento(fp);
            valorPagar = valorPagar - fp.getValor();
            valorjTextField.setText(Formatacao.foramtarDoubleString(valorPagar));
            bandeirajTextField.setText("");
            numeroParcelasjTextField.setText("1");
            formaPagamentojTextField.setText("");
            itensFormas = new DefaultListModel();
            formaPagamentojList.setModel(itensFormas);
            bandeirajTextField.requestFocus();
            gerarModelFormaPagamento();
        }
    }//GEN-LAST:event_valorjTextFieldKeyPressed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        float valorCartao =0;
        for(int i=0;i<formaRecebidas.size();i++){
            if (formaRecebidas.get(i).getBandeiraCartao()!=3){
                valorCartao = valorCartao + formaRecebidas.get(i).getValor();
            }
        }
        Formapagamento fp = new Formapagamento();
        FormaPagamentoController formaPagamentoController = new FormaPagamentoController();
        fp = formaPagamentoController.getFormapagamento(10);
        if (fp!=null){
            fp.setValor(valorCartao);
            salvarFormaPagamento(fp);
        }
        telaVenda.gerarFormaPagamentoCartao();
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList bandeirajList;
    private javax.swing.JTextField bandeirajTextField;
    private javax.swing.JList formaPagamentojList;
    private javax.swing.JTable formaPagamentojTable;
    private javax.swing.JTextField formaPagamentojTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField numeroParcelasjTextField;
    private javax.swing.JTextField valorjTextField;
    // End of variables declaration//GEN-END:variables

    public void gerarListaBandeirasCartao(){
        BandeiraCartaoController bandeiraCartaoController = new BandeiraCartaoController();
        listaBandeira = bandeiraCartaoController.listarBandeirasCartao();
        if (listaBandeira!=null){
            itensBandeira = new DefaultListModel();
            for(int i=0;i<listaBandeira.size();i++){
                itensBandeira.addElement(listaBandeira.get(i));
            }
            bandeirajList.setModel(itensBandeira);
        }
    }
    
    public void gerarListaFormasPagamento(int idBandeiraCartao){
        FormaPagamentoController formaPagamentoController = new FormaPagamentoController();
        listaFormaPagamentoCartao = formaPagamentoController.getFormaPagamentoBandeiraCartao(idBandeiraCartao);
        if (listaFormaPagamentoCartao!=null){
            itensFormas = new DefaultListModel();
            for(int i=0;i<listaFormaPagamentoCartao.size();i++){
                itensFormas.addElement(listaFormaPagamentoCartao.get(i));   
            }
            formaPagamentojList.setModel(itensFormas);
        }
    }
    
    public void gerarModelFormaPagamento(){
        FormaPagamentoController formaPagamentoController = new FormaPagamentoController();
        formaRecebidas = formaPagamentoController.listarFormaPagamentoValor();
        if (formaRecebidas==null){
            formaRecebidas = new ArrayList<Formapagamento>();
        }
        modelForma = new FormaPagamentoTableModel(formaRecebidas);
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(SwingConstants.RIGHT);
        this.setLocationRelativeTo(this);
        formaPagamentojTable.setModel(modelForma);
        formaPagamentojTable.getColumnModel().getColumn(0).setPreferredWidth(10);
        formaPagamentojTable.getColumnModel().getColumn(1).setPreferredWidth(50);
        formaPagamentojTable.getColumnModel().getColumn(2).setCellRenderer(renderer);
        formaPagamentojTable.getColumnModel().getColumn(2).setPreferredWidth(20);
        formaPagamentojTable.repaint();
    }   
    
    public void salvarFormaPagamento(Formapagamento formapagamento){
        FormaPagamentoController formaPagamentoController = new FormaPagamentoController();
        formaPagamentoController.salvarFormapagamento(formapagamento);
    }
}
