/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmAberturaCaixa.java
 *
 * Created on 29/10/2010, 11:26:25
 */

package Interface;

import Controller.FechaCaixaController;
import Controller.UsuariosController;
import Regras.Config;
import Regras.Formatacao;
import Regras.UsuarioLogado;
import java.awt.Dialog.ModalExclusionType;
import java.sql.Time;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import model.Fechacaixa;
import model.Usuarios;
import telas.Vendas.FrmTelaVenda;

/**
 *
 * @author Woverine
 */
public class FrmAberturaCaixa extends javax.swing.JFrame {

    private Fechacaixa fechaCaixa;
    Config config = new Config();
    private UsuarioLogado usuarioLogado;

    /** Creates new form FrmAberturaCaixa */
    public FrmAberturaCaixa(UsuarioLogado usuarioLogado) {
        this.fechaCaixa = new Fechacaixa();
        this.usuarioLogado = usuarioLogado;
        initComponents();
        config.carregarConfiguracao();
        this.setLocationRelativeTo(null);
        DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        datajTextField.setText(df.format(new Date()));
        this.setModalExclusionType(ModalExclusionType.NO_EXCLUDE);
        valorjTextField1.requestFocus();
        valorjTextField1.selectAll();
        verificarAbertura();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        valorjTextField1 = new javax.swing.JTextField();
        datajTextField = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        confirnajButton = new javax.swing.JButton();
        cancelajButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Abertura de Caixa");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 340, -1));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 340, -1));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Data Abertura");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Valor Abertura");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        valorjTextField1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        valorjTextField1.setForeground(new java.awt.Color(102, 102, 102));
        valorjTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        valorjTextField1.setText("0,00");
        jPanel5.add(valorjTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 35, 160, -1));

        datajTextField.setEditable(false);
        datajTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        datajTextField.setForeground(new java.awt.Color(102, 102, 102));
        datajTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        datajTextField.setText("20/09/2010");
        jPanel5.add(datajTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, 180, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 370, 80));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 60));

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        confirnajButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tick.png"))); // NOI18N
        confirnajButton.setText("Confirmar");
        confirnajButton.setToolTipText("Confirma abertura do caixa");
        confirnajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirnajButtonActionPerformed(evt);
            }
        });
        jPanel6.add(confirnajButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        cancelajButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cross.png"))); // NOI18N
        cancelajButton.setText("Cancelar");
        cancelajButton.setToolTipText("Cancela abertura do Caixa");
        cancelajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelajButtonActionPerformed(evt);
            }
        });
        jPanel6.add(cancelajButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 360, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelajButtonActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_cancelajButtonActionPerformed

        @SuppressWarnings("static-access")
    private void confirnajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirnajButtonActionPerformed
            this.fechaCaixa.setDataFechamento(new Date());
            Time hora = new Time(new Date().getTime());
            this.fechaCaixa.setHora(hora);
            this.fechaCaixa.setValorFechamento(0.f);
            this.fechaCaixa.setEmpresa(config.getEmpresa().getIdempresa());
            this.fechaCaixa.setCaixa(config.getIdCaixa());
            this.fechaCaixa.setValorAbertura(new Formatacao().formatarStringfloat(valorjTextField1.getText()));
            this.fechaCaixa.setOperador(usuarioLogado.getUsuario().getLogin());
            this.fechaCaixa.setCreditoDevolucao(0.0);
            this.fechaCaixa.setSituacao("ABERTO");
            this.fechaCaixa.setUsuarios(usuarioLogado.getUsuario().getIdusuarios());
            FechaCaixaController fechaCaixaController = new FechaCaixaController();
            this.fechaCaixa = fechaCaixaController.salvar(fechaCaixa);
            finalizarUsuario(this.fechaCaixa.getIdfechaCaixa());
            new FrmTelaVenda(this.fechaCaixa, this.config, usuarioLogado);
            this.dispose();
    }//GEN-LAST:event_confirnajButtonActionPerformed
    
    public void localizarCaixa(){
        FechaCaixaController fechaCaixaController = new FechaCaixaController();
        this.fechaCaixa = fechaCaixaController.getFechaCaixa(config.getIdCaixa(), usuarioLogado.getUsuario().getIdusuarios());
        if(this.fechaCaixa==null){
            this.fechaCaixa= new Fechacaixa();
            this.fechaCaixa.setValorFechamento(0.0f);
        }
    }
        
    public boolean verificarAbertura() {
        localizarCaixa();
        if (this.fechaCaixa.getValorFechamento()==0){
            if (this.fechaCaixa.getIdfechaCaixa()!=null){
                new FrmTelaVenda(fechaCaixa, config, usuarioLogado);
                return true;
            }
        }
        
        if ((this.fechaCaixa.getValorFechamento()>0) && (this.fechaCaixa.getIdfechaCaixa()!=null)){
            float valorFechamento = this.fechaCaixa.getValorFechamento();
            this.fechaCaixa = new Fechacaixa();
            this.fechaCaixa.setValorAbertura(valorFechamento);
            valorjTextField1.setText(Formatacao.foramtarFloatString(valorFechamento));
            this.setVisible(true);
            return true;
        }
        
        if ((this.fechaCaixa.getValorFechamento()==0) && (this.fechaCaixa.getIdfechaCaixa()==null)){
            this.fechaCaixa = new Fechacaixa();
            valorjTextField1.setText("0,00");
            valorjTextField1.setEditable(true);
            valorjTextField1.selectAll();
            this.setVisible(true);
            return true;
        }
        return true;
    }

    public void finalizarUsuario(int idFechaCaixa){
        UsuariosController usuariosController = new UsuariosController();
        Usuarios usuarios = new Usuarios();
        usuarios = usuarioLogado.getUsuario();
        usuarios.setIdFechaCaixa(idFechaCaixa);
        usuariosController.salvarUsuario(usuarios);
    }
   

    
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelajButton;
    private javax.swing.JButton confirnajButton;
    private javax.swing.JTextField datajTextField;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField valorjTextField1;
    // End of variables declaration//GEN-END:variables

}
