

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmConsultaPlanoContas.java
 *
 * Created on 23/09/2009, 12:29:02
 */
package Interface;

import controler.ItelaRetirada;
import facade.PlanoContaFacade;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import model.Planoconta;

/**
 *
 * @author Wolverine
 */
public class FrmConsultaPlanoContas extends javax.swing.JFrame {
    
    private ItelaRetirada telaRetirada;
    private List<Planoconta>  listaPlanoContas;

    public FrmConsultaPlanoContas(ItelaRetirada telaRetirada) {
        try {
            PlanoContaFacade facade = new PlanoContaFacade();
            listaPlanoContas = facade.consultarPlanoconta();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());

        }
        this.telaRetirada= telaRetirada;
        initComponents();
        setModel();
        this.setLocationRelativeTo(null);
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PlanoContasjPanel = new javax.swing.JPanel();
        descricaoPlanoContasjTextField = new javax.swing.JTextField();
        descricaojLabel = new javax.swing.JLabel();
        BarradeTarefasjToolBar = new javax.swing.JToolBar();
        SeparadordeTarefasjSeparator = new javax.swing.JToolBar.Separator();
        jScrollPane2 = new javax.swing.JScrollPane();
        consultaPlanoContasjTable = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        cancelarjButton = new javax.swing.JButton();
        confirmarjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta Plano de Contas");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PlanoContasjPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PlanoContasjPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        URL url = this.getClass().getResource("/imagens/logo_mini.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        try{
            UIManager.setLookAndFeel("com.birosoft.liquid.LiquidLookAndFeel");
        }catch (Exception e){
            e.printStackTrace();
        }
        PlanoContasjPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        descricaoPlanoContasjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                descricaoPlanoContasjTextFieldKeyPressed(evt);
            }
        });
        PlanoContasjPanel.add(descricaoPlanoContasjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 410, -1));

        descricaojLabel.setText("Descrição");
        PlanoContasjPanel.add(descricaojLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        BarradeTarefasjToolBar.setFloatable(false);
        BarradeTarefasjToolBar.setRollover(true);
        BarradeTarefasjToolBar.add(SeparadordeTarefasjSeparator);

        PlanoContasjPanel.add(BarradeTarefasjToolBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 560, -1));

        consultaPlanoContasjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Título 1", "Título 2"
            }
        ));
        consultaPlanoContasjTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        consultaPlanoContasjTable.getTableHeader().setReorderingAllowed(false);
        consultaPlanoContasjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultaPlanoContasjTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(consultaPlanoContasjTable);

        PlanoContasjPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 570, 250));

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancelarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/door_in.png"))); // NOI18N
        cancelarjButton.setText("Fechar");
        cancelarjButton.setToolTipText("Sari da consulta de Plano de Contas");
        cancelarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarjButtonActionPerformed(evt);
            }
        });
        jPanel6.add(cancelarjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        confirmarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tick.png"))); // NOI18N
        confirmarjButton.setText("Confirmar");
        confirmarjButton.setToolTipText("Confirma consulta de Plano de contas");
        confirmarjButton.setEnabled(false);
        confirmarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarjButtonActionPerformed(evt);
            }
        });
        jPanel6.add(confirmarjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        PlanoContasjPanel.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 530, 40));

        getContentPane().add(PlanoContasjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void descricaoPlanoContasjTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descricaoPlanoContasjTextFieldKeyPressed
        try {
            PlanoContaFacade facade = new PlanoContaFacade();
            listaPlanoContas = facade.consultarPlanoconta(descricaoPlanoContasjTextField.getText());
            setModel();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }//GEN-LAST:event_descricaoPlanoContasjTextFieldKeyPressed
    private void consultaPlanoContasjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaPlanoContasjTableMouseClicked
        if (evt.getClickCount() == 1) {
            confirmarjButton.setEnabled(true);
        }else if (evt.getClickCount() == 2 ) {
            int linha = consultaPlanoContasjTable.getSelectedRow();
            if (linha >= 0) {
                Planoconta planoContas = model.listaPlanoConta.get(linha);
                telaRetirada.consultarConta(planoContas);
                this.dispose();
            }
        }
}//GEN-LAST:event_consultaPlanoContasjTableMouseClicked

    private void cancelarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarjButtonActionPerformed
        this.dispose();
}//GEN-LAST:event_cancelarjButtonActionPerformed

    private void confirmarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarjButtonActionPerformed
        int linha = consultaPlanoContasjTable.getSelectedRow();
        if (linha >= 0) {
            Planoconta planoContas = this.listaPlanoContas.get(linha);
            telaRetirada.consultarConta(planoContas);
            this.dispose();
        }
}//GEN-LAST:event_confirmarjButtonActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar BarradeTarefasjToolBar;
    private javax.swing.JPanel PlanoContasjPanel;
    private javax.swing.JToolBar.Separator SeparadordeTarefasjSeparator;
    private javax.swing.JButton cancelarjButton;
    private javax.swing.JButton confirmarjButton;
    private javax.swing.JTable consultaPlanoContasjTable;
    private javax.swing.JTextField descricaoPlanoContasjTextField;
    private javax.swing.JLabel descricaojLabel;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    private ConsultaPlanoContasTableModel model;

    public void setModel() {
        try {
           model = new ConsultaPlanoContasTableModel(listaPlanoContas);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());

            model = new ConsultaPlanoContasTableModel(new ArrayList<Planoconta>());
        }
        consultaPlanoContasjTable.setModel(model);
        consultaPlanoContasjTable.getColumnModel().getColumn(0).setMaxWidth(60);
    }
}
