/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmRetirada.java
 *
 * Created on 29/07/2011, 15:35:06
 */
package Interface;

import Regras.Config;
import Regras.Formatacao;
import controler.ItelaRetirada;
import facade.MovimentoCaixaFacade;
import facade.RetiradaFacade;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import model.Fechacaixa;
import model.Movimentocaixa;
import model.Planoconta;
import model.Retirada;

/**
 *
 * @author Wolverine
 */
public class FrmRetirada extends javax.swing.JFrame implements ItelaRetirada {
    
    private List<Retirada> listaRetirada;
    private Fechacaixa fechaCaixa;
    private RetiradasTableModel retiradaModel;
    private Retirada retirada;
    private Config config;
    

    /** Creates new form FrmRetirada */
    public FrmRetirada(Fechacaixa fechaCaixa, Config config) {
        this.fechaCaixa = fechaCaixa;
        this.config = config;
        initComponents();
        URL url = this.getClass().getResource("/imagens/logo_mini.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        this.setLocationRelativeTo(null);
        try{
            UIManager.setLookAndFeel("com.birosoft.liquid.LiquidLookAndFeel");
        }catch (Exception e){
        }
        gerarJTableRetira();
        
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        valorDinheirojTextField = new javax.swing.JTextField();
        valorChequejTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        valorChequePrejTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        contajTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        descricaojTextField = new javax.swing.JTextField();
        historicojTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        retiradajTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        adicionarjButton = new javax.swing.JButton();
        fecharjButton = new javax.swing.JButton();
        excluirjButton = new javax.swing.JButton();
        cancelarjButton = new javax.swing.JButton();
        confirmarjButton = new javax.swing.JButton();
        buscaBancojButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Retiradas");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel1.setText("Valor Dinheiro");

        valorDinheirojTextField.setEditable(false);
        valorDinheirojTextField.setFont(new java.awt.Font("Tahoma", 0, 18));
        valorDinheirojTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        valorDinheirojTextField.setText("0,00");
        valorDinheirojTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                valorDinheirojTextFieldFocusGained(evt);
            }
        });

        valorChequejTextField.setEditable(false);
        valorChequejTextField.setFont(new java.awt.Font("Tahoma", 0, 18));
        valorChequejTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        valorChequejTextField.setText("0,00");
        valorChequejTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                valorChequejTextFieldFocusGained(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel2.setText("Valor Cheque");

        valorChequePrejTextField.setEditable(false);
        valorChequePrejTextField.setFont(new java.awt.Font("Tahoma", 0, 18));
        valorChequePrejTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        valorChequePrejTextField.setText("0,00");
        valorChequePrejTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                valorChequePrejTextFieldFocusGained(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel3.setText("Valor Cheque Pré");

        contajTextField.setEditable(false);
        contajTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        contajTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        contajTextField.setText("000");
        contajTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contajTextFieldFocusGained(evt);
            }
        });
        contajTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                contajTextFieldKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel4.setText("Código Conta");

        descricaojTextField.setEditable(false);
        descricaojTextField.setFont(new java.awt.Font("Tahoma", 0, 18));
        descricaojTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        historicojTextField.setFont(new java.awt.Font("Tahoma", 0, 18));
        historicojTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel5.setText("Histórico");

        retiradajTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Valor Dinheiro", "Valor Cheque", "Valor Cheque Pré", "Total", "Conta", "Histórico"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        retiradajTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retiradajTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(retiradajTable);
        retiradajTable.getColumnModel().getColumn(0).setResizable(false);
        retiradajTable.getColumnModel().getColumn(0).setPreferredWidth(10);
        retiradajTable.getColumnModel().getColumn(1).setResizable(false);
        retiradajTable.getColumnModel().getColumn(1).setPreferredWidth(10);
        retiradajTable.getColumnModel().getColumn(2).setResizable(false);
        retiradajTable.getColumnModel().getColumn(2).setPreferredWidth(30);
        retiradajTable.getColumnModel().getColumn(3).setResizable(false);
        retiradajTable.getColumnModel().getColumn(3).setPreferredWidth(10);
        retiradajTable.getColumnModel().getColumn(4).setResizable(false);
        retiradajTable.getColumnModel().getColumn(4).setPreferredWidth(10);
        retiradajTable.getColumnModel().getColumn(5).setResizable(false);
        retiradajTable.getColumnModel().getColumn(5).setPreferredWidth(300);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel6.setText("Descrição Conta");

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adicionarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/note.png"))); // NOI18N
        adicionarjButton.setText("Adcionar");
        adicionarjButton.setToolTipText("Adicionar uma nova retirada");
        adicionarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarjButtonActionPerformed(evt);
            }
        });
        jPanel6.add(adicionarjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        fecharjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/door_in.png"))); // NOI18N
        fecharjButton.setText("Fechar");
        fecharjButton.setToolTipText("Sair das retiradas");
        fecharjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharjButtonActionPerformed(evt);
            }
        });
        jPanel6.add(fecharjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, -1));

        excluirjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cross.png"))); // NOI18N
        excluirjButton.setText("Excluir");
        excluirjButton.setToolTipText("Excluir retirada");
        excluirjButton.setEnabled(false);
        excluirjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirjButtonActionPerformed(evt);
            }
        });
        jPanel6.add(excluirjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 90, -1));

        cancelarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cross.png"))); // NOI18N
        cancelarjButton.setText("Cancelar");
        cancelarjButton.setToolTipText("cancela uma nova retirada");
        cancelarjButton.setEnabled(false);
        cancelarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarjButtonActionPerformed(evt);
            }
        });
        jPanel6.add(cancelarjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        confirmarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tick.png"))); // NOI18N
        confirmarjButton.setText("Confirmar");
        confirmarjButton.setToolTipText("Cofirma uma nova retirada");
        confirmarjButton.setEnabled(false);
        confirmarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarjButtonActionPerformed(evt);
            }
        });
        jPanel6.add(confirmarjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        buscaBancojButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/magnifier.png"))); // NOI18N
        buscaBancojButton1.setToolTipText("Pesquisa Plano de Contas");
        buscaBancojButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaBancojButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(valorDinheirojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(valorChequejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(valorChequePrejTextField)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(contajTextField)
                                        .addComponent(jLabel4))
                                    .addGap(2, 2, 2)
                                    .addComponent(buscaBancojButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(descricaojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(historicojTextField, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valorChequePrejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valorChequejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valorDinheirojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buscaBancojButton1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(contajTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(descricaojTextField, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(28, 28, 28)))))
                .addGap(7, 7, 7)
                .addComponent(historicojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarjButtonActionPerformed
        this.retirada = new Retirada();
        this.retirada.setFechacaixa(this.fechaCaixa.getIdfechaCaixa());
        valorDinheirojTextField.requestFocus();
        cancelarjButton.setEnabled(true);
        adicionarjButton.setEnabled(false);
        confirmarjButton.setEnabled(true);
        excluirjButton.setEnabled(false);
        fecharjButton.setEnabled(false);
        valorDinheirojTextField.setEditable(true);
        valorChequePrejTextField.setEditable(true);
        valorChequejTextField.setEditable(true);
}//GEN-LAST:event_adicionarjButtonActionPerformed

    private void fecharjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharjButtonActionPerformed
        this.dispose();
}//GEN-LAST:event_fecharjButtonActionPerformed

    private void excluirjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirjButtonActionPerformed
        int linha = retiradajTable.getSelectedRow();
        if (linha>=0){
            RetiradaFacade retiradaFacade = new RetiradaFacade();
            this.retirada = listaRetirada.get(linha);
            if (retirada.getIdMovimentoCaixa()>0){
                excluirLancamentoCaixa(retirada.getIdMovimentoCaixa());
            }
            try {
                retiradaFacade.excluir(retirada);
                limparCampos();
                gerarJTableRetira();
            } catch (Exception ex) {
                Logger.getLogger(FrmRetirada.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_excluirjButtonActionPerformed

    private void cancelarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarjButtonActionPerformed
        this.retirada = null;
        cancelarjButton.setEnabled(false);
        adicionarjButton.setEnabled(true);
        confirmarjButton.setEnabled(false);
        excluirjButton.setEnabled(false);
        fecharjButton.setEnabled(true);
        valorDinheirojTextField.setEditable(false);
        valorChequePrejTextField.setEditable(false);
        valorChequejTextField.setEditable(false);
        limparCampos();
        gerarJTableRetira();
    }//GEN-LAST:event_cancelarjButtonActionPerformed

    private void confirmarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarjButtonActionPerformed
        if (validarRetirada()) {
            this.retirada.setValorDinheiro(Formatacao.ConvercaoMonetariaFloat(valorDinheirojTextField.getText()));
            this.retirada.setValorCheque(Formatacao.ConvercaoMonetariaFloat(valorChequejTextField.getText()));
            this.retirada.setValorChequePre(Formatacao.ConvercaoMonetariaFloat(valorChequePrejTextField.getText()));
            this.retirada.setHistorico(historicojTextField.getText());
            this.retirada.setEmpresa(config.getEmpresa().getIdempresa());
            int idCaixa = 0;
            boolean resultado = JOptionPane.showConfirmDialog(null, "Lançar Movimento de Caixa JGDynamic?", "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE) == 0;
            if (resultado) {
                idCaixa = lancarCaixaRetaguarda();
            }
            this.retirada.setIdMovimentoCaixa(idCaixa);
            RetiradaFacade retiradaFacade = new RetiradaFacade();
            try {
                retiradaFacade.salvar(retirada);
                gerarJTableRetira();
                limparCampos();
                confirmarjButton.setEnabled(false);
                cancelarjButton.setEnabled(false);
                excluirjButton.setEnabled(false);
                fecharjButton.setEnabled(true);
                adicionarjButton.setEnabled(true);
                valorDinheirojTextField.setEditable(false);
                valorChequePrejTextField.setEditable(false);
                valorChequejTextField.setEditable(false);
            } catch (Exception ex) {
                Logger.getLogger(FrmRetirada.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_confirmarjButtonActionPerformed

    private void valorDinheirojTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valorDinheirojTextFieldFocusGained
        valorDinheirojTextField.selectAll();
    }//GEN-LAST:event_valorDinheirojTextFieldFocusGained

    private void valorChequejTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valorChequejTextFieldFocusGained
        valorChequejTextField.selectAll();
    }//GEN-LAST:event_valorChequejTextFieldFocusGained

    private void valorChequePrejTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valorChequePrejTextFieldFocusGained
       valorChequePrejTextField.selectAll();
    }//GEN-LAST:event_valorChequePrejTextFieldFocusGained

    private void contajTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contajTextFieldFocusGained
        contajTextField.selectAll();
    }//GEN-LAST:event_contajTextFieldFocusGained

    private void contajTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contajTextFieldKeyPressed
       
    }//GEN-LAST:event_contajTextFieldKeyPressed

    private void retiradajTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retiradajTableMouseClicked
        int linha = retiradajTable.getSelectedRow();
        if (linha>=0){
            excluirjButton.setEnabled(true);
        }
    }//GEN-LAST:event_retiradajTableMouseClicked

    private void buscaBancojButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaBancojButton1ActionPerformed
        if (this.retirada!=null){
            new FrmConsultaPlanoContas(this);
        }
}//GEN-LAST:event_buscaBancojButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarjButton;
    private javax.swing.JButton buscaBancojButton1;
    private javax.swing.JButton cancelarjButton;
    private javax.swing.JButton confirmarjButton;
    private javax.swing.JTextField contajTextField;
    private javax.swing.JTextField descricaojTextField;
    private javax.swing.JButton excluirjButton;
    private javax.swing.JButton fecharjButton;
    private javax.swing.JTextField historicojTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable retiradajTable;
    private javax.swing.JTextField valorChequePrejTextField;
    private javax.swing.JTextField valorChequejTextField;
    private javax.swing.JTextField valorDinheirojTextField;
    // End of variables declaration//GEN-END:variables

    public void gerarJTableRetira(){
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(SwingConstants.RIGHT);
        listaRetirada = new ArrayList<Retirada>();
        RetiradaFacade retiradaFacade = new RetiradaFacade();
        try {
            listaRetirada = retiradaFacade.listarRetiradas(fechaCaixa);
        } catch (SQLException ex) {
            Logger.getLogger(FrmRetirada.class.getName()).log(Level.SEVERE, null, ex);
        }
        retiradaModel = new RetiradasTableModel(listaRetirada);
        retiradajTable.setModel(retiradaModel);
        retiradajTable.setColumnSelectionAllowed(true);
        retiradajTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        retiradajTable.setShowVerticalLines(false);
        retiradajTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(retiradajTable);
        retiradajTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        retiradajTable.getColumnModel().getColumn(0).setCellRenderer(renderer);
        retiradajTable.getColumnModel().getColumn(0).setResizable(false);
        retiradajTable.getColumnModel().getColumn(0).setPreferredWidth(20);
        retiradajTable.getColumnModel().getColumn(1).setCellRenderer(renderer);
        retiradajTable.getColumnModel().getColumn(1).setResizable(false);
        retiradajTable.getColumnModel().getColumn(1).setPreferredWidth(20);
        retiradajTable.getColumnModel().getColumn(2).setCellRenderer(renderer);
        retiradajTable.getColumnModel().getColumn(2).setResizable(false);
        retiradajTable.getColumnModel().getColumn(2).setPreferredWidth(30);
        retiradajTable.getColumnModel().getColumn(3).setCellRenderer(renderer);
        retiradajTable.getColumnModel().getColumn(3).setResizable(false);
        retiradajTable.getColumnModel().getColumn(3).setPreferredWidth(20);
        retiradajTable.getColumnModel().getColumn(4).setResizable(false);
        retiradajTable.getColumnModel().getColumn(4).setPreferredWidth(20);
        retiradajTable.getColumnModel().getColumn(5).setResizable(false);
        retiradajTable.getColumnModel().getColumn(5).setPreferredWidth(300);
        retiradajTable.repaint();
    }

    public void consultarConta(Planoconta conta) {
        this.retirada.setPlanoconta(conta.getIdplanoconta());
        descricaojTextField.setText(conta.getDescricao());
        contajTextField.setText(conta.getNumeroConta());
        historicojTextField.requestFocus();
    }
    
    public void limparCampos(){
        valorChequePrejTextField.setText("0,00");
        valorChequejTextField.setText("0,00");
        valorDinheirojTextField.setText("0,00");
        contajTextField.setText("000");
        historicojTextField.setText("");
        descricaojTextField.setText("");
    }
    
    public int lancarCaixaRetaguarda(){
        String historico = JOptionPane.showInputDialog(rootPane, "Informe o Histórico de Movimento", this.retirada.getHistorico());
        Movimentocaixa lancar = new Movimentocaixa();
        lancar.setDataMovimento(this.fechaCaixa.getDataFechamento());
        lancar.setDescricao(historico);
        lancar.setEmpresa(this.fechaCaixa.getEmpresa());
        lancar.setPlanoconta(this.retirada.getPlanoconta());
        lancar.setUsuarioLancamento(this.fechaCaixa.getOperador());
        float valor = retirada.getValorCheque().floatValue() + retirada.getValorChequePre().floatValue() + retirada.getValorDinheiro().floatValue();
        lancar.setValorSaida(valor);
        lancar.setValorEntrada(0f);
        MovimentoCaixaFacade movimentoCaixaFacade = new MovimentoCaixaFacade();
        int idCaixa = 0;
        try {
            movimentoCaixaFacade.salvarCaixa(lancar);
            idCaixa = movimentoCaixaFacade.ultimaMovimentoCaixaSalvo();
        } catch (Exception ex) {
            Logger.getLogger(FrmRetirada.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Erro Salvar Moviemnto Caixa");
        }
        return idCaixa;
    }
    
    public void excluirLancamentoCaixa(int idLancamento){
        MovimentoCaixaFacade movimentoCaixaFacade = new MovimentoCaixaFacade();
        try {
            movimentoCaixaFacade.excluirCaixa(idLancamento);
        } catch (Exception ex) {
            Logger.getLogger(FrmRetirada.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Erro exluir Caixa");
        }
    }
    
    
    public boolean validarRetirada(){
        if (historicojTextField.getText().length() <= 0) {
            JOptionPane.showMessageDialog(null, "Campo histórico ce de preenchimento obrigatório");
            historicojTextField.requestFocus();;
            return false;
        }else {
            if (this.retirada.getPlanoconta()==0){
                JOptionPane.showMessageDialog(null,"Selecione uma conta");
                contajTextField.requestFocus();
                return false;
            }else {
                return true;
            }
        }
    }

}

