/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PesquisaAssociado.java
 *
 * Created on 20/09/2009, 15:29:05
 */
package telas.contasReceber;


import Controller.ClienteController;
import controler.Config;
import controler.ItelaVenda;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import model.Cliente;



public final class FrmConsultaClientes extends javax.swing.JFrame {

    private ConsultaClienteTableModel modelCliente;
    List<Cliente> listaCliente;
    private ItelaVenda telaVenda;
    
    public FrmConsultaClientes(ItelaVenda telaVenda) {
        this.telaVenda = telaVenda;
        listaCliente = new ArrayList<Cliente>();
        initComponents();
        URL url = this.getClass().getResource("/imagens/logo_mini.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        this.setLocationRelativeTo(null);
        carregarTodosClientes();
        nomejTextField.requestFocus();
        setVisible(true);
    }
    

    /** Creates new form PesquisaAssociado */
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AssociadosjPanel = new javax.swing.JPanel();
        nomejTextField = new javax.swing.JTextField();
        NomedoAssociadojLabel = new javax.swing.JLabel();
        codigojTextField = new javax.swing.JTextField();
        NomedoAssociadojLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientejTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de Cliente");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AssociadosjPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        AssociadosjPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        AssociadosjPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nomejTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nomejTextFieldKeyPressed(evt);
            }
        });
        AssociadosjPanel.add(nomejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 410, -1));

        NomedoAssociadojLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        NomedoAssociadojLabel.setText("Código");
        AssociadosjPanel.add(NomedoAssociadojLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        codigojTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                codigojTextFieldKeyPressed(evt);
            }
        });
        AssociadosjPanel.add(codigojTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 90, -1));

        NomedoAssociadojLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        NomedoAssociadojLabel1.setText("Nome / Razão Social");
        AssociadosjPanel.add(NomedoAssociadojLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        clientejTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "null", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        clientejTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientejTableMouseClicked(evt);
            }
        });
        clientejTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                clientejTableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(clientejTable);
        clientejTable.getColumnModel().getColumn(0).setResizable(false);
        clientejTable.getColumnModel().getColumn(1).setResizable(false);
        clientejTable.getColumnModel().getColumn(2).setResizable(false);
        clientejTable.getColumnModel().getColumn(3).setResizable(false);
        clientejTable.getColumnModel().getColumn(4).setResizable(false);
        clientejTable.getColumnModel().getColumn(5).setResizable(false);

        AssociadosjPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 1000, 310));

        getContentPane().add(AssociadosjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codigojTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigojTextFieldKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            if (codigojTextField.getText().length()>0){
                carregarConsultaClienteId(Integer.parseInt(codigojTextField.getText()));
            }
        }
    }//GEN-LAST:event_codigojTextFieldKeyPressed

    private void nomejTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomejTextFieldKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            if (nomejTextField.getText().length()>0){
                carregarConsultaClienteNome(nomejTextField.getText());
            }
        }
    }//GEN-LAST:event_nomejTextFieldKeyPressed

    private void clientejTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clientejTableKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            int linha = clientejTable.getSelectedRow();
            if (linha>=0){
                telaVenda.consultarClienteRecebimneto(listaCliente.get(linha));
                this.dispose();
            }
        }
    }//GEN-LAST:event_clientejTableKeyPressed

    private void clientejTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientejTableMouseClicked
        if (evt.getClickCount()==2){
            int linha = clientejTable.getSelectedRow();
            if (linha>=0){
                telaVenda.consultarClienteRecebimneto(listaCliente.get(linha));
                this.dispose();
            }
        }
    }//GEN-LAST:event_clientejTableMouseClicked
    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AssociadosjPanel;
    private javax.swing.JLabel NomedoAssociadojLabel;
    private javax.swing.JLabel NomedoAssociadojLabel1;
    private javax.swing.JTable clientejTable;
    private javax.swing.JTextField codigojTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomejTextField;
    // End of variables declaration//GEN-END:variables
    
    private void carregarConsultaClienteNome(String nome){
        ClienteController clienteController = new ClienteController();
        listaCliente = clienteController.consultarClienteNome(nome);
        setModelCliente();
    }
    
    public void carregarConsultaClienteId(int idCliente){
        ClienteController clienteController = new ClienteController();
        Cliente cliente = new Cliente();
        cliente = clienteController.consultarClienteId(idCliente);
        if (cliente!=null){
            listaCliente.add(cliente);
        }else {
            listaCliente = new ArrayList<Cliente>();
        }
        setModelCliente();
    }
    
    public void carregarTodosClientes(){
        ClienteController clienteController = new ClienteController();
        listaCliente = clienteController.consultarCliente();
        setModelCliente();
    }
    
    public void setModelCliente(){
        if (listaCliente!=null){
            modelCliente = new ConsultaClienteTableModel(listaCliente);
        }else modelCliente = new ConsultaClienteTableModel(new ArrayList<Cliente>());
        clientejTable.setModel(modelCliente);
        clientejTable.getColumnModel().getColumn(0).setPreferredWidth(20);
        clientejTable.getColumnModel().getColumn(1).setPreferredWidth(350);
        clientejTable.getColumnModel().getColumn(2).setPreferredWidth(20);
        clientejTable.getColumnModel().getColumn(3).setPreferredWidth(20);
        clientejTable.getColumnModel().getColumn(4).setPreferredWidth(100);
        clientejTable.getColumnModel().getColumn(5).setPreferredWidth(20);
        clientejTable.repaint();
    }
}

