/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.Vendas;

import Regras.Config;
import Regras.Formatacao;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JOptionPane;
import negocios.ECFBematech;

/**
 *
 * @author Wolverine
 */
public class FrmMenuFiscal extends javax.swing.JFrame {
    
    private ECFBematech ecf;
    
    private String datePattern;
    private String maskPattern;
    private char placeHolder;
    private Config config;

    /**
     * Creates new form FrmMenuFiscal
     */
    public FrmMenuFiscal(Config config) {
        datePattern = "dd/MM/yyyy";
        maskPattern = "##/##/##";
        this.config = config;
        placeHolder = '_';
        ecf = new ECFBematech();
        initComponents();
        URL url = this.getClass().getResource("/imagens/logo_mini.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        faixabuttonGroup = new javax.swing.ButtonGroup();
        saidabuttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        adicionarPlanoContasjButton4 = new javax.swing.JButton();
        adicionarPlanoContasjButton5 = new javax.swing.JButton();
        adicionarPlanoContasjButton6 = new javax.swing.JButton();
        adicionarPlanoContasjButton7 = new javax.swing.JButton();
        adicionarPlanoContasjButton8 = new javax.swing.JButton();
        adicionarPlanoContasjButton9 = new javax.swing.JButton();
        adicionarPlanoContasjButton10 = new javax.swing.JButton();
        adicionarPlanoContasjButton13 = new javax.swing.JButton();
        adicionarPlanoContasjButton14 = new javax.swing.JButton();
        adicionarPlanoContasjButton15 = new javax.swing.JButton();
        adicionarPlanoContasjButton16 = new javax.swing.JButton();
        adicionarPlanoContasjButton17 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        periodojRadioButton = new javax.swing.JRadioButton();
        crzjRadioButton = new javax.swing.JRadioButton();
        coojRadioButton = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        dataInicialjDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
            maskPattern, placeHolder));
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    dataFinaljDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
        maskPattern, placeHolder));
jPanel6 = new javax.swing.JPanel();
impressorajRadioButton = new javax.swing.JRadioButton();
arquivojRadioButton = new javax.swing.JRadioButton();
jPanel7 = new javax.swing.JPanel();
nomeArquivojTextField = new javax.swing.JTextField();

setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
jLabel1.setText("Menu Fiscal");

javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
jPanel1.setLayout(jPanel1Layout);
jPanel1Layout.setHorizontalGroup(
    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
        .addGap(18, 18, 18))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    adicionarPlanoContasjButton4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
    adicionarPlanoContasjButton4.setText("Leitura X - F3");
    adicionarPlanoContasjButton4.setToolTipText("Cadastro de Produtos");
    adicionarPlanoContasjButton4.setMaximumSize(new java.awt.Dimension(80, 90));
    adicionarPlanoContasjButton4.setMinimumSize(new java.awt.Dimension(80, 90));
    adicionarPlanoContasjButton4.setName(""); // NOI18N
    adicionarPlanoContasjButton4.setPreferredSize(new java.awt.Dimension(80, 90));
    adicionarPlanoContasjButton4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            adicionarPlanoContasjButton4ActionPerformed(evt);
        }
    });

    adicionarPlanoContasjButton5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
    adicionarPlanoContasjButton5.setText("LMFC - F4");
    adicionarPlanoContasjButton5.setToolTipText("Cadastro de Produtos");
    adicionarPlanoContasjButton5.setMaximumSize(new java.awt.Dimension(80, 90));
    adicionarPlanoContasjButton5.setMinimumSize(new java.awt.Dimension(80, 90));
    adicionarPlanoContasjButton5.setName(""); // NOI18N
    adicionarPlanoContasjButton5.setPreferredSize(new java.awt.Dimension(80, 90));
    adicionarPlanoContasjButton5.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            adicionarPlanoContasjButton5ActionPerformed(evt);
        }
    });

    adicionarPlanoContasjButton6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
    adicionarPlanoContasjButton6.setText("Espelho MDF - F6");
    adicionarPlanoContasjButton6.setToolTipText("Cadastro de Produtos");
    adicionarPlanoContasjButton6.setMaximumSize(new java.awt.Dimension(80, 90));
    adicionarPlanoContasjButton6.setMinimumSize(new java.awt.Dimension(80, 90));
    adicionarPlanoContasjButton6.setName(""); // NOI18N
    adicionarPlanoContasjButton6.setPreferredSize(new java.awt.Dimension(80, 90));
    adicionarPlanoContasjButton6.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            adicionarPlanoContasjButton6ActionPerformed(evt);
        }
    });

    adicionarPlanoContasjButton7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
    adicionarPlanoContasjButton7.setText("LMFS - F5");
    adicionarPlanoContasjButton7.setToolTipText("Cadastro de Produtos");
    adicionarPlanoContasjButton7.setMaximumSize(new java.awt.Dimension(80, 90));
    adicionarPlanoContasjButton7.setMinimumSize(new java.awt.Dimension(80, 90));
    adicionarPlanoContasjButton7.setName(""); // NOI18N
    adicionarPlanoContasjButton7.setPreferredSize(new java.awt.Dimension(80, 90));
    adicionarPlanoContasjButton7.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            adicionarPlanoContasjButton7ActionPerformed(evt);
        }
    });

    adicionarPlanoContasjButton8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
    adicionarPlanoContasjButton8.setText("Arquivo MDF - F7");
    adicionarPlanoContasjButton8.setToolTipText("Cadastro de Produtos");
    adicionarPlanoContasjButton8.setMaximumSize(new java.awt.Dimension(80, 90));
    adicionarPlanoContasjButton8.setMinimumSize(new java.awt.Dimension(80, 90));
    adicionarPlanoContasjButton8.setName(""); // NOI18N
    adicionarPlanoContasjButton8.setPreferredSize(new java.awt.Dimension(80, 90));
    adicionarPlanoContasjButton8.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            adicionarPlanoContasjButton8ActionPerformed(evt);
        }
    });

    adicionarPlanoContasjButton9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
    adicionarPlanoContasjButton9.setText("Tab. Produto - F8");
    adicionarPlanoContasjButton9.setToolTipText("Cadastro de Produtos");
    adicionarPlanoContasjButton9.setMaximumSize(new java.awt.Dimension(80, 90));
    adicionarPlanoContasjButton9.setMinimumSize(new java.awt.Dimension(80, 90));
    adicionarPlanoContasjButton9.setName(""); // NOI18N
    adicionarPlanoContasjButton9.setPreferredSize(new java.awt.Dimension(80, 90));
    adicionarPlanoContasjButton9.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            adicionarPlanoContasjButton9ActionPerformed(evt);
        }
    });

    adicionarPlanoContasjButton10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
    adicionarPlanoContasjButton10.setText("Estoque - F9");
    adicionarPlanoContasjButton10.setToolTipText("Cadastro de Produtos");
    adicionarPlanoContasjButton10.setMaximumSize(new java.awt.Dimension(80, 90));
    adicionarPlanoContasjButton10.setMinimumSize(new java.awt.Dimension(80, 90));
    adicionarPlanoContasjButton10.setName(""); // NOI18N
    adicionarPlanoContasjButton10.setPreferredSize(new java.awt.Dimension(80, 90));
    adicionarPlanoContasjButton10.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            adicionarPlanoContasjButton10ActionPerformed(evt);
        }
    });

    adicionarPlanoContasjButton13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
    adicionarPlanoContasjButton13.setText("Vendas Período");
    adicionarPlanoContasjButton13.setToolTipText("Cadastro de Produtos");
    adicionarPlanoContasjButton13.setMaximumSize(new java.awt.Dimension(80, 90));
    adicionarPlanoContasjButton13.setMinimumSize(new java.awt.Dimension(80, 90));
    adicionarPlanoContasjButton13.setName(""); // NOI18N
    adicionarPlanoContasjButton13.setPreferredSize(new java.awt.Dimension(80, 90));
    adicionarPlanoContasjButton13.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            adicionarPlanoContasjButton13ActionPerformed(evt);
        }
    });

    adicionarPlanoContasjButton14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
    adicionarPlanoContasjButton14.setText("Identificação do PAF-ECF");
    adicionarPlanoContasjButton14.setToolTipText("Cadastro de Produtos");
    adicionarPlanoContasjButton14.setMaximumSize(new java.awt.Dimension(80, 90));
    adicionarPlanoContasjButton14.setMinimumSize(new java.awt.Dimension(80, 90));
    adicionarPlanoContasjButton14.setName(""); // NOI18N
    adicionarPlanoContasjButton14.setPreferredSize(new java.awt.Dimension(80, 90));
    adicionarPlanoContasjButton14.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            adicionarPlanoContasjButton14ActionPerformed(evt);
        }
    });

    adicionarPlanoContasjButton15.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
    adicionarPlanoContasjButton15.setText("Movimento por ECF");
    adicionarPlanoContasjButton15.setToolTipText("Cadastro de Produtos");
    adicionarPlanoContasjButton15.setMaximumSize(new java.awt.Dimension(80, 90));
    adicionarPlanoContasjButton15.setMinimumSize(new java.awt.Dimension(80, 90));
    adicionarPlanoContasjButton15.setName(""); // NOI18N
    adicionarPlanoContasjButton15.setPreferredSize(new java.awt.Dimension(80, 90));
    adicionarPlanoContasjButton15.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            adicionarPlanoContasjButton15ActionPerformed(evt);
        }
    });

    adicionarPlanoContasjButton16.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
    adicionarPlanoContasjButton16.setText("Tab. Indice Técnico de Produção");
    adicionarPlanoContasjButton16.setToolTipText("Cadastro de Produtos");
    adicionarPlanoContasjButton16.setMaximumSize(new java.awt.Dimension(80, 90));
    adicionarPlanoContasjButton16.setMinimumSize(new java.awt.Dimension(80, 90));
    adicionarPlanoContasjButton16.setName(""); // NOI18N
    adicionarPlanoContasjButton16.setPreferredSize(new java.awt.Dimension(80, 90));
    adicionarPlanoContasjButton16.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            adicionarPlanoContasjButton16ActionPerformed(evt);
        }
    });

    adicionarPlanoContasjButton17.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
    adicionarPlanoContasjButton17.setText("Meios de Pagamento");
    adicionarPlanoContasjButton17.setToolTipText("Cadastro de Produtos");
    adicionarPlanoContasjButton17.setMaximumSize(new java.awt.Dimension(80, 90));
    adicionarPlanoContasjButton17.setMinimumSize(new java.awt.Dimension(80, 90));
    adicionarPlanoContasjButton17.setName(""); // NOI18N
    adicionarPlanoContasjButton17.setPreferredSize(new java.awt.Dimension(80, 90));
    adicionarPlanoContasjButton17.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            adicionarPlanoContasjButton17ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(adicionarPlanoContasjButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(adicionarPlanoContasjButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(adicionarPlanoContasjButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(adicionarPlanoContasjButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(adicionarPlanoContasjButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(adicionarPlanoContasjButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(adicionarPlanoContasjButton13, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                        .addComponent(adicionarPlanoContasjButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(adicionarPlanoContasjButton16, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                        .addComponent(adicionarPlanoContasjButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(adicionarPlanoContasjButton14, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                        .addComponent(adicionarPlanoContasjButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGap(10, 10, 10))
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(adicionarPlanoContasjButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(adicionarPlanoContasjButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(adicionarPlanoContasjButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(adicionarPlanoContasjButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(adicionarPlanoContasjButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(adicionarPlanoContasjButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(adicionarPlanoContasjButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(adicionarPlanoContasjButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(adicionarPlanoContasjButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(adicionarPlanoContasjButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(adicionarPlanoContasjButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(adicionarPlanoContasjButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Faixa de Dados"));

    faixabuttonGroup.add(periodojRadioButton);
    periodojRadioButton.setSelected(true);
    periodojRadioButton.setText("0 - Perído");

    faixabuttonGroup.add(crzjRadioButton);
    crzjRadioButton.setText("1 - CRZ");

    faixabuttonGroup.add(coojRadioButton);
    coojRadioButton.setText("2 - COO");

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(periodojRadioButton)
                .addComponent(crzjRadioButton)
                .addComponent(coojRadioButton))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel4Layout.setVerticalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(periodojRadioButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(crzjRadioButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(coojRadioButton)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Período"));

    dataInicialjDateChooser.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            dataInicialjDateChooserFocusGained(evt);
        }
    });

    jLabel2.setText("De");

    jLabel3.setText("a");

    dataFinaljDateChooser.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            dataFinaljDateChooserFocusGained(evt);
        }
    });

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel2)
                .addComponent(jLabel3))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(dataInicialjDateChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(dataFinaljDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel5Layout.setVerticalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addComponent(dataInicialjDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(dataFinaljDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addComponent(jLabel2)
                    .addGap(24, 24, 24)
                    .addComponent(jLabel3)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Saída"));

    saidabuttonGroup.add(impressorajRadioButton);
    impressorajRadioButton.setSelected(true);
    impressorajRadioButton.setText("Impressora");

    saidabuttonGroup.add(arquivojRadioButton);
    arquivojRadioButton.setText("Arquivo");

    javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
    jPanel6.setLayout(jPanel6Layout);
    jPanel6Layout.setHorizontalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel6Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(impressorajRadioButton)
                .addComponent(arquivojRadioButton))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel6Layout.setVerticalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel6Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(impressorajRadioButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(arquivojRadioButton)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Arquivo"));

    nomeArquivojTextField.setEditable(false);
    nomeArquivojTextField.setText("c:\\temp\\RETORNO.TXT");

    javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
    jPanel7.setLayout(jPanel7Layout);
    jPanel7Layout.setHorizontalGroup(
        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel7Layout.createSequentialGroup()
            .addComponent(nomeArquivojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
    );
    jPanel7Layout.setVerticalGroup(
        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(nomeArquivojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarPlanoContasjButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarPlanoContasjButton4ActionPerformed
        ecf.leituraX();
    }//GEN-LAST:event_adicionarPlanoContasjButton4ActionPerformed

    private void adicionarPlanoContasjButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarPlanoContasjButton5ActionPerformed
        emitirLMF("C");
    }//GEN-LAST:event_adicionarPlanoContasjButton5ActionPerformed

    private void adicionarPlanoContasjButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarPlanoContasjButton6ActionPerformed
        emitirEspelhoMDF();
    }//GEN-LAST:event_adicionarPlanoContasjButton6ActionPerformed

    private void adicionarPlanoContasjButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarPlanoContasjButton7ActionPerformed
        emitirLMF("S");
    }//GEN-LAST:event_adicionarPlanoContasjButton7ActionPerformed

    private void adicionarPlanoContasjButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarPlanoContasjButton8ActionPerformed
        emitirArquivoMDF();
    }//GEN-LAST:event_adicionarPlanoContasjButton8ActionPerformed

    private void adicionarPlanoContasjButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarPlanoContasjButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adicionarPlanoContasjButton9ActionPerformed

    private void adicionarPlanoContasjButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarPlanoContasjButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adicionarPlanoContasjButton10ActionPerformed

    private void adicionarPlanoContasjButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarPlanoContasjButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adicionarPlanoContasjButton13ActionPerformed

    private void adicionarPlanoContasjButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarPlanoContasjButton14ActionPerformed
        ecf.identificacaoPAFECF(this.config.getEmissorECF().getNumeroSerie());
    }//GEN-LAST:event_adicionarPlanoContasjButton14ActionPerformed

    private void adicionarPlanoContasjButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarPlanoContasjButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adicionarPlanoContasjButton15ActionPerformed

    private void adicionarPlanoContasjButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarPlanoContasjButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adicionarPlanoContasjButton16ActionPerformed

    private void adicionarPlanoContasjButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarPlanoContasjButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adicionarPlanoContasjButton17ActionPerformed

    private void dataInicialjDateChooserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataInicialjDateChooserFocusGained

    }//GEN-LAST:event_dataInicialjDateChooserFocusGained

    private void dataFinaljDateChooserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataFinaljDateChooserFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dataFinaljDateChooserFocusGained

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarPlanoContasjButton10;
    private javax.swing.JButton adicionarPlanoContasjButton13;
    private javax.swing.JButton adicionarPlanoContasjButton14;
    private javax.swing.JButton adicionarPlanoContasjButton15;
    private javax.swing.JButton adicionarPlanoContasjButton16;
    private javax.swing.JButton adicionarPlanoContasjButton17;
    private javax.swing.JButton adicionarPlanoContasjButton4;
    private javax.swing.JButton adicionarPlanoContasjButton5;
    private javax.swing.JButton adicionarPlanoContasjButton6;
    private javax.swing.JButton adicionarPlanoContasjButton7;
    private javax.swing.JButton adicionarPlanoContasjButton8;
    private javax.swing.JButton adicionarPlanoContasjButton9;
    private javax.swing.JRadioButton arquivojRadioButton;
    private javax.swing.JRadioButton coojRadioButton;
    private javax.swing.JRadioButton crzjRadioButton;
    private com.toedter.calendar.JDateChooser dataFinaljDateChooser;
    private com.toedter.calendar.JDateChooser dataInicialjDateChooser;
    private javax.swing.ButtonGroup faixabuttonGroup;
    private javax.swing.JRadioButton impressorajRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField nomeArquivojTextField;
    private javax.swing.JRadioButton periodojRadioButton;
    private javax.swing.ButtonGroup saidabuttonGroup;
    // End of variables declaration//GEN-END:variables

    public void emitirLMF(String tipo){
        if (periodojRadioButton.isSelected()){
            String dataInicial = Formatacao.ConvercaoDataPadrao(dataInicialjDateChooser.getDate());
            String dataFinal = Formatacao.ConvercaoDataPadrao(dataFinaljDateChooser.getDate());
            if (impressorajRadioButton.isSelected()){
                ecf.LeituraMemoriaFiscalDataImpressora(dataInicial, dataFinal, tipo);
            }else {
                if (arquivojRadioButton.isSelected()){
                    ecf.leituraMemoriaFiscalDataArquivo(dataInicial, dataFinal, tipo);
                }
            }
        }else {
            if (crzjRadioButton.isSelected()){
                String reducaoInicial = JOptionPane.showInputDialog("Nº Redução Inicial");
                String reducaoFinal = JOptionPane.showInputDialog("Nº Redução Final");
                if (impressorajRadioButton.isSelected()){
                ecf.LeituraMemoriaFiscalReducaoImpressora(reducaoInicial, reducaoFinal, tipo);
            }else {
                if (arquivojRadioButton.isSelected()){
                    ecf.leituraMemoriaFiscalReducaoArquivo(reducaoInicial, reducaoFinal, tipo);
                }
            }
            }
        }
    }
    
    public void emitirLMFS(){
        if (periodojRadioButton.isSelected()){
            String dataInicial = Formatacao.ConvercaoDataPadrao(dataInicialjDateChooser.getDate());
            String dataFinal = Formatacao.ConvercaoDataPadrao(dataFinaljDateChooser.getDate());
            String tipo="S";
            if (impressorajRadioButton.isSelected()){
                ecf.LeituraMemoriaFiscalDataImpressora(dataInicial, dataFinal, tipo);
            }else {
                if (arquivojRadioButton.isSelected()){
                    ecf.leituraMemoriaFiscalDataArquivo(dataInicial, dataFinal, tipo);
                }
            }
        }
    }
    
    public void emitirEspelhoMDF(){
        if (periodojRadioButton.isSelected()){
            String dataInicial = Formatacao.ConvercaoDataPadrao(dataInicialjDateChooser.getDate());
            String dataFinal = Formatacao.ConvercaoDataPadrao(dataFinaljDateChooser.getDate());
            String nomeArquivo = nomeArquivojTextField.getSelectedText();
            ecf.espelhoMDF(nomeArquivo, dataInicial, dataFinal, "D", "1");
        }else {
            if (coojRadioButton.isSelected()){
                String cooInicial = JOptionPane.showInputDialog("Informe COO Inicial");
                String cooFinal = JOptionPane.showInputDialog("Informe COO Final");
                String nomeArquivo = nomeArquivojTextField.getSelectedText();
                ecf.espelhoMDF(nomeArquivo, cooInicial, cooFinal, "C", "1");
            }
        }
    }
    
    public void emitirArquivoMDF(){
        if (periodojRadioButton.isSelected()){
            String dataInicial = Formatacao.ConvercaoDataPadrao(dataInicialjDateChooser.getDate());
            String dataFinal = Formatacao.ConvercaoDataPadrao(dataFinaljDateChooser.getDate());
            String nomeArquivo = nomeArquivojTextField.getSelectedText();
            ecf.arquivoMDF(dataInicial, dataFinal, "D", "1",1);
        }else {
            if (coojRadioButton.isSelected()){
                String cooInicial = JOptionPane.showInputDialog("Informe COO Inicial");
                String cooFinal = JOptionPane.showInputDialog("Informe COO Final");
                String nomeArquivo = nomeArquivojTextField.getSelectedText();
                ecf.arquivoMDF(cooInicial, cooFinal, "C", "1",1);
            }
        }
    }

}
